Set fso = CreateObject("Scripting.FileSystemObject")
Set file = fso.CreateTextFile("LOVE-LETTER-FOR-YOU.txt", True)

file.WriteLine "LOVE-LETTER-FOR-YOU"
file.WriteLine ""
file.WriteLine "If I could fold my heart into an envelope,"
file.WriteLine "I would seal it with the quiet hope"
file.WriteLine "that when you open it,"
file.WriteLine "you feel how softly you are held in my thoughts."
file.WriteLine ""
file.WriteLine "You are the gentle pause between my worries,"
file.WriteLine "the warmth in ordinary afternoons,"
file.WriteLine "the reason even silence feels full"
file.WriteLine "instead of empty."
file.WriteLine ""
file.WriteLine "I carry your name"
file.WriteLine "like a favorite song—"
file.WriteLine "humming it under my breath"
file.WriteLine "when the world grows loud."
file.WriteLine ""
file.WriteLine "If distance ever stretches thin between us,"
file.WriteLine "know this:"
file.WriteLine "my love does not measure itself in miles"
file.WriteLine "but in moments—"
file.WriteLine "in the way your laughter lingers,"
file.WriteLine "in the way your eyes turn simple days into stories."
file.WriteLine ""
file.WriteLine "You are not just someone I love."
file.WriteLine "You are the place my heart"
file.WriteLine "returns to,"
file.WriteLine "again and again."
file.WriteLine ""
file.WriteLine "Forever yours,"
file.WriteLine "in ink, in breath, in everything I am."

file.Close

MsgBox "LOVE-LETTER-FOR-YOU.txt has been created successfully!", vbInformation, "Done"